# Generated by Django 4.0.5 on 2022-06-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.CharField(max_length=500, null=True)),
                ('picture2', models.CharField(max_length=500, null=True)),
                ('picture3', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
