# Generated by Django 4.0.5 on 2022-06-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_backgroundimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=250)),
                ('frimg', models.CharField(max_length=400, null=True)),
                ('sdimg', models.CharField(max_length=400, null=True)),
                ('thimg', models.CharField(max_length=400, null=True)),
                ('ftimg', models.CharField(max_length=400)),
                ('amenities', models.CharField(max_length=300)),
                ('price', models.IntegerField(null=True)),
                ('numofpeople', models.IntegerField(null=True)),
                ('checkin', models.DateField(auto_now=True)),
                ('checkout', models.DateField(auto_now=True)),
            ],
        ),
    ]
