# Generated by Django 4.0.5 on 2022-08-02 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_remove_reservations_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='checkin',
            field=models.DateField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='checkout',
            field=models.DateField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='current_hotel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.hotels'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='current_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
