# Generated by Django 4.0.5 on 2022-08-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_reservations_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='checkin',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='checkout',
            field=models.DateField(default=None),
        ),
    ]
